---
- import_tasks: prereqs.yml

- name: Copy and Configure Sizing Template
  template:
    src: "sizing.j2"
    dest: "{{ target_dir }}/sizing-validation.yaml"
    owner: "{{ vunet_user }}"
    group: "vunet"
    mode: '0644'

- name: Download vuSmartMaps Tarball
  shell: wget --user={{ download_user }} --password={{ download_pass }} --no-check-certificate -O {{ target_dir }}/vuSmartMaps_offline_NG-3.0.tar.gz https://download.vunetsystems.com/_Downloads_/_vuDocker_/3.0/vuSmartMaps_offline_NG-3.0.tar.gz
  args:
    creates: "{{ target_dir }}/vuSmartMaps_offline_NG-3.0.tar.gz"

- name: Log download status
  debug:
    msg: "Download task completed. Last 20 lines of wget output shown above."

- name: Extract Tarball
  unarchive:
    src: "{{ target_dir }}/vuSmartMaps_offline_NG-3.0.tar.gz"
    dest: "{{ target_dir }}/"
    remote_src: yes
    owner: "{{ vunet_user }}"
    group: "vunet"

- name: Log extraction status
  shell: echo "Tarball extraction completed."
  args:
    chdir: "{{ target_dir }}"

- name: Run Installer in Background (Nohup)
  shell: |
    nohup ./build/launcher_linux_x86 \
      --sizing sizing-validation.yaml \
      --ignore-preflight \
      --debug > install_log.txt 2>&1 &
  args:
    chdir: "{{ target_dir }}"
  environment:
    username: "{{ vunet_user }}"
    private_key_path: ".ssh/id_rsa"
  become_user: "{{ vunet_user }}" # Run as vunet user
  async: 45
  poll: 0

- name: Log installer status
  shell: tail -20 install_log.txt
  args:
    chdir: "{{ target_dir }}"
  become_user: "{{ vunet_user }}"