primary_images:
  location: "https://ghcr.io"
  username: "CPQPQ8bQ7W5Krv68CvZJ6w=="
  password: "cywl9KXhH9zYeUcofEzQxrG/s2DGpCZ9y2UMfhfBlSPqFS6+mnUmtCYNP1DXOnOo"
  email: "devsecops@vunetsystems.com"
sizing:
  category:
    - "data-store-optimised"
    - "data-hub-optimised"
    - "core-services-optimised"
  env_name: "vm"
  node:
    - ip_address: "216.48.184.251"
      is_master: true
      storage:
        default: ["/data1"]
        host: ["/data1"]
  # vustream & vublock related components
  deployments:
    - name: pipeline
      resource_limit:
        min:
          cpu: "0.5"
          memory: "128Mi"
        max:
          cpu: "1"
          memory: "256Mi"
  # service information
  services:
    # longhorn
    - name: "longhorn"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
      disk:
        default: 2Gi
    # minio-operator
    - name: "minio-operator"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # minio-tenant
    - name: "minio-tenant"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
      disk:
        default: 20Gi
    # postgresql
    - name: "postgresql"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
      disk:
        default: 10Gi
    # kafka-broker
    - name: "kafka-broker"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.75"
          memory: "2Gi"
      replica: 1
      disk:
        host: 5Gi
      pv_mapper:
        - name: "0"
          size: "12Gi"
          hostPath: "/data1"
          nodeName: "e2e-101-251"
          nodeIP: "216.48.184.251"
          dirPath: "kafka_dir"
    # kafka-zookeeper
    - name: "kafka-zookeeper"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.75"
          memory: "2Gi"
      replica: 1
      disk:
        default: 5Gi
    # kafka-connect
    - name: "kafka-connect"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # clickhouse-operator
    - name: "ch-operator"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # clickhouse-keeper
    - name: "ch-keeper"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
      disk:
        host: 5Gi
      pv_mapper:
        - name: "0"
          size: "6Gi"
          hostPath: "/data1"
          nodeName: "e2e-101-251"
          nodeIP: "216.48.184.251"
          dirPath: "clickhouse-keeper"
    # clickhouse database
    - name: "ch-database"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "6Gi"
      replica: 1
      disk:
        host: 5Gi
      pv_mapper:
        - name: "warm-chi-clickhouse-vusmart-0-0-0"
          size: "12Gi"
          hostPath: "/data1"
          nodeName: "e2e-101-251"
          nodeIP: "216.48.184.251"
          dirPath: "clickhouse-warm"
        - name: "clickhouse-data-volume-chi-clickhouse-vusmart-0-0-0"
          size: "12Gi"
          hostPath: "/data1"
          nodeName: "e2e-101-251"
          nodeIP: "216.48.184.251"
          dirPath: "clickhouse"
      config_override:
        persistence.host.hot.enabled: "true"
        persistence.host.warm.enabled: "true"
    # telegraf-vusmart
    - name: "telegraf-vusmart"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "1Gi"
      replica: 1
    # telegraf-infra
    - name: "telegraf-infra"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "1Gi"
      replica: 1
    # redis
    - name: "redis"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # orchestration
    - name: "orchestrator"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "1Gi"
      replica: 1
    # traefik
    - name: "traefik"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # renderer-service
    - name: "nairobi-renderer"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # reporter service
    - name: "nairobi-reporter"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # nairobi
    - name: "nairobi-app"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
      disk:
        default: 2Gi
    # keycloak
    - name: "keycloak"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # denver
    - name: "denver"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "4Gi"
      replica: 1
    # vuinterface
    - name: "vuinterface"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "4Gi"
      replica: 1
      config_override:
        env.0.value: "216.48.184.251"
    # dao
    - name: "dao"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "4Gi"
      replica: 1
    # alert
    - name: "alert"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "1Gi"
      replica: 1
    #vublock-service
    - name: "vublock"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    #vublock-store
    - name: "vublock-store"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1
    # post-jobs
    - name: "post-jobs"
      resource_limit:
        min:
          cpu: "0.3"
          memory: "500Mi"
        max:
          cpu: "0.5"
          memory: "2Gi"
      replica: 1